version: '3.4'

# Use root/password as user/password credentials
services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --skip-character-set-client-handshake
    environment: 
      MYSQL_ROOT_PASSWORD: password
    ports:
        - 33306:3306
    volumes: 
        - ./mysql-init:/docker-entrypoint-initdb.d
        - ./mysql-local-data:/var/lib/mysql
        - ./mysql-conf:/etc/mysql/conf.d/
